### ISSUE TITLE
如何关闭服务

### ISSUE THREAD

**Issue by wangxiaolei5** [lvming6816077/wecircleCode#1]
你好，我下载您的项目运行一次之后没有使用命令行关闭启动的服务，导致我现在本机启动其他项目后也是使用的您的后端服务，除了换端口8080之外，我怎样可以启动其他服务

**Comment by lvming6816077** [comment]
如果是Node服务，直接在控制台ctrl+c即可关闭

**Comment by wangxiaolei5** [comment]
> 如果是Node服务，直接在控制台ctrl+c即可关闭

你好，我现在是启动本地的任何其他项目都运行的是下载的您的项目，node进程已经关闭了

**Comment by lvming6816077** [comment]
@wangxiaolei5  您之前提到的端口是8080，本项目的后端使用的是3000端口，确认一下是不是其他服务影响了你的业务。https://github.com/lvming6816077/wecircleCode/blob/master/wecircleServer/bin/server.js#L16

**Comment by wangxiaolei5** [comment]
> https://github.com/lvming6816077/wecircleCode/blob/master/wecircleServer/bin/server.js#L16
您好，因为这边ui加载的还是您的项目的，我不太记得当时是怎么启动的了

**Comment by lvming6816077** [comment]
netstat -aon|findstr "8080"  看下是哪个进程占用的 然后找到对应程序 tasklist|findstr "xxxxx" 
然后kill掉

**Comment by wangxiaolei5** [comment]
> netstat -aon|findstr "8080" 看下是哪个进程占用的 然后找到对应程序 tasklist|findstr "xxxxx"
> 然后kill掉
您好，我清除浏览器缓存之后，目前其他项目的代码是正常加载了，谢谢您帮我这么详细解答，我之后也会根据您这个课程项目来进行学习的。
